name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Validar archivos
        run: |
          echo "Validando proyecto..."
          test -f index.html
          test -f README.md
          echo "Validación completada correctamente."